---
- name: Initiate forceful power reset
  hosts: bmcs
  remote_user: root
  become: False
  gather_facts: False
  vars_files:
    - gagarin_vault
  tasks:
  - name: Restart system power forcefully
    community.general.redfish_command:
      category: Systems
      command: PowerForceRestart
      baseuri: "{{ ip }}"
      username: "{{ username }}"
      password: "{{ password }}"
    tags:
      - reboot
