---
- name: Send Redfish command to reset server power gracefully
  hosts: bmcs
  remote_user: root
  become: False
  gather_facts: False
  vars_files:
    - gagarin_vault
  tasks:
  - name: Restart system power gracefully
    community.general.redfish_command:
      category: Systems
      command: PowerGracefulRestart
      baseuri: "{{ ip }}"
      username: "{{ username }}"
      password: "{{ password }}"
    tags:
      - reboot
