---
- name: Fetch BMC/UEFI versions via RedFish
  hosts: bmcs
  remote_user: root
  become: False
  gather_facts: False
  vars_files:
    - gagarin_vault
  tasks:
  - name: Get Firmware inventory
    community.general.redfish_info:
      category: Update
      command: GetFirmwareInventory
      baseuri: "{{ ip }}"
      username: "{{ username }}"
      password: "{{ password }}"
    register: firmware_result
  - ansible.builtin.debug:
      msg: "{{ item.Version }}"
    loop: "{{ firmware_result.redfish_facts.firmware.entries }}"
    loop_control:
      label: "{{ item.Id }}"
