---
- name: Work with Gagarin BMC via Redfish
  hosts: bmcs
  remote_user: root
  become: False
  gather_facts: False
  vars_files:
    - gagarin_bmc
  tasks:
  - name: Get CPU inventory
    community.general.redfish_info:
      category: Systems
      command: GetCpuInventory
      baseuri: "{{ ip }}"
      username: "{{ username }}"
      password: "{{ password }}"
    register: cpu_result
  - ansible.builtin.debug:
      msg: "{{ cpu_result.redfish_facts.cpu.entries | to_nice_json }}"
  - name: Get Memory information
    community.general.redfish_info:
      category: Systems
      command: GetMemoryInventory
      baseuri: "{{ ip }}"
      username: "{{ username }}"
      password: "{{ password }}"
    register: mem_result
  - ansible.builtin.debug:
      msg: "{{ mem_result.redfish_facts.memory.entries | to_nice_json }}"
  - name: Get default inventory information
    community.general.redfish_info:
      baseuri: "{{ ip }}"
      username: "{{ username }}"
      password: "{{ password }}"
    register: gen_result
  - ansible.builtin.debug:
      msg: "{{ gen_result.redfish_facts | to_nice_json }}"
  - name: Output summary
    template:
      src: summary.j2
      dest: "/tmp/{{ inventory_hostname }}.txt"

