---
- name: Work with Gagarin BMC via Redfish
  hosts: bmcs
  remote_user: root
  become: False
  gather_facts: False
  vars_files:
    - gagarin_vault
  tasks:
  - name: Get CPU inventory
    community.general.redfish_info:
      category: Systems
      command: GetCpuInventory
      baseuri: "{{ ip }}"
      username: "{{ username }}"
      password: "{{ password }}"
    register: cpu_result
  - ansible.builtin.debug:
      msg: "{{ cpu_result.redfish_facts.cpu.entries | to_nice_json }}"
    when: False
  - name: Get Memory information
    community.general.redfish_info:
      category: Systems
      command: GetMemoryInventory
      baseuri: "{{ ip }}"
      username: "{{ username }}"
      password: "{{ password }}"
    register: mem_result
  - ansible.builtin.debug:
      msg: "{{ mem_result.redfish_facts.memory.entries | to_nice_json }}"
    when: False
  - name: Get default inventory information
    community.general.redfish_info:
      baseuri: "{{ ip }}"
      username: "{{ username }}"
      password: "{{ password }}"
    register: gen_result
  - ansible.builtin.debug:
      msg: "{{ gen_result.redfish_facts | to_nice_json }}"
    when: False
  - name: Create output directory
    file:
      path: /opt/awx/reports/{{ gen_result.redfish_facts.system.entries.0.1.SerialNumber }}
      state: directory
  - name: Output inventory summary
    template:
      src: summary.j2
      dest: "/opt/awx/reports/{{ gen_result.redfish_facts.system.entries.0.1.SerialNumber }}/inventory.txt"
      force: True
