---
- name: Fetch UEFI version via RedFish
  hosts: bmcs
  remote_user: root
  become: False
  gather_facts: False
  vars_files:
    - gagarin_vault
  tasks:
  - name: Get System inventory
    community.general.redfish_info:
      category: Systems
      command: GetSystemInventory
      baseuri: "{{ ip }}"
      username: "{{ username }}"
      password: "{{ password }}"
    register: system_result
  - ansible.builtin.debug:
      msg: "{{ system_result.redfish_facts.system.entries.0.1.BiosVersion | to_nice_json }}"
