---
- name: Upgrade BMC firmware via curl request
  hosts: bmcs
  remote_user: root
  become: False
  gather_facts: False
  vars_files:
    - gagarin_vault
  tasks:
  - name: Simple update with curl
    shell:
      cmd: |
        curl -s -k -H "Content-Type: application/octet-stream" -X POST -T "/opt/awx/BMC/{{ BMC_tar | default('latest') }}" "https://{{ username }}:{{ password }}@{{ ip }}/redfish/v1/UpdateService"
    ignore_errors: True
