---
- name: Install Zabbix agent for remote monitoring
  hosts: hosts
  become: True
  vars_files:
    - gagarin_vault
  roles:
     - role: community.zabbix.zabbix_agent
       zabbix_agent_server: 192.168.88.6
       zabbix_agent_serveractive: 192.168.88.6
       zabbix_url: http://172.18.1.8:8888/zabbix/
       zabbix_api_use: True # use zabbix_api_create_hosts and/or zabbix_api_create_hostgroup from 0.8.0
       zabbix_api_create_hosts: True
       zabbix_api_user: "{{ zabbix_user }}"
       zabbix_api_pass: "{{ zabbix_pass }}"
       zabbix_create_host: present
       zabbix_host_groups:
         - Linux servers
       zabbix_link_templates:
         - Template OS Linux by Zabbix agent
